name: "Tools - Validate JSON Schema"

on:
  push:
    branches: [ "customize" ]
  pull_request:
    branches: [ "customize" ]


jobs:
  validate-json-schema:
    name: Validate JSON Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
