---
name: Ubuntu - Build docker image for Ubuntu Slim

"on":
  workflow_dispatch:

permissions:
  contents: read

env:
  os: "ubuntu-slim"
  
  REGISTRY: ${{ vars.REGISTRY }}
  REGISTRY_ACCOUNT: ${{ vars.REGISTRY_ACCOUNT }}
  REGISTRY_REPO: ${{ vars.REGISTRY_REPO }}
  REGISTRY_REPO_TAG_CACHE_NAME: ${{ vars.REGISTRY_REPO_TAG_CACHE_NAME }}
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}

concurrency:
  group: "runner-image-build-${{ github.workflow }}"
  cancel-in-progress: false
  
jobs:
  check-requirements:
    name: Requirements
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        vars: [REGISTRY, REGISTRY_ACCOUNT, REGISTRY_REPO, REGISTRY_REPO_TAG_CACHE_NAME, REGISTRY_PLATFORMS]

    steps:
      - name: Check if variable exist
        run: |
          if [[ -z ${!VARNAME} ]]; then
            echo "Variable \"${VARNAME}\" not found. Please create the variable under \"Repository variables\" \(https://github.com/${{ github.REPOSITORY}}/settings/variables/actions\)."
            exit 1
          fi
        env:
          VARNAME: "${{ matrix.vars }}"


  Set-Variables:
    runs-on: ubuntu-latest
    needs: check-requirements

    permissions:
      contents: read

    steps:
      - name: Assign ENV variable to workflow variable
        id: env
        run: |
           echo "os=$os" >> $GITHUB_OUTPUT
     
    outputs:      
      os: ${{ steps.env.outputs.os }}
     
     
  Trigger-CollectInformations:
    needs: Set-Variables
    
    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/ubutnu_trigger-collect-informations.yml
    with:
      os: ${{ needs.Set-Variables.outputs.os }}


  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations
    
    permissions:
      contents: write
      pull-requests: write
    
    uses: ./.github/workflows/ubuntu_trigger-build-new-container.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
      readme_file: ${{ needs.Trigger-CollectInformations.outputs.ReadmeFile }}
      gh_pr_labels: ${{ needs.Trigger-CollectInformations.outputs.GitHubPrLabels }}
      
    secrets: inherit
